Fixed DOCKER_FROM_IMAGE for app deployment Removed/replaced moodle references Adjusted APP_NAME env vars

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -3,13 +3,13 @@
 name: 🧹️ Clean-up
 
 env:
-  APP: ${{ github.repository }}
+  APP_NAME: ${{ github.repository }}
   USER: ${{ github.actor }}
 
 on:
   workflow_call:
     inputs:
-      APP:
+      APP_NAME:
         required: true
         type: string
       BRANCH:
@@ -159,11 +159,11 @@ jobs:
             oc delete configmap $configmap_name
             echo "DELETED configmap $configmap_name"
           fi
-          if [[ `oc describe configmap moodle-env 2>&1` =~ "NotFound" ]]; then
-            echo "Configmap moodle-env NOT FOUND: Skipping..."
+          if [[ `oc describe configmap ${{ inputs.APP_NAME }}-env 2>&1` =~ "NotFound" ]]; then
+            echo "Configmap ${{ inputs.APP_NAME }}-env NOT FOUND: Skipping..."
           else
-            oc delete configmap moodle-env
-            echo "DELETED configmap moodle-env"
+            oc delete configmap ${{ inputs.APP_NAME }}-env
+            echo "DELETED configmap ${{ inputs.APP_NAME }}-env"
           fi
           if ! [[ `oc describe service ${{ inputs.WEB_NAME }} 2>&1` =~ "NotFound" ]]; then
             oc delete service ${{ inputs.WEB_NAME }}
@@ -196,9 +196,9 @@ jobs:
             oc delete configmap $app_configmap_name
             echo "DELETED configmap $app_configmap_name"
           fi
-          if ! [[ `oc describe pvc moodle-env 2>&1` =~ "NotFound" ]]; then
-            oc delete pvc moodle-env
-            echo "DELETED pvc moodle-env"
+          if ! [[ `oc describe pvc ${{ inputs.APP_NAME }}-env 2>&1` =~ "NotFound" ]]; then
+            oc delete pvc ${{ inputs.APP_NAME }}-env
+            echo "DELETED pvc ${{ inputs.APP_NAME }}-env"
           fi
           if ! [[ `oc describe service ${{ inputs.PHP_NAME }} 2>&1` =~ "NotFound" ]]; then
             oc delete service ${{ inputs.PHP_NAME }}
@@ -265,12 +265,12 @@ jobs:
       - name: 🧹️ Clean Upgrade Job
         id: clean-upgrade-job
         run: |
-          if [[ `oc describe job moodle-upgrade 2>&1` =~ "NotFound" ]]; then
-            echo "moodle-upgrade NOT FOUND: Skipping..."
+          if [[ `oc describe job ${{ inputs.APP_NAME }}-upgrade 2>&1` =~ "NotFound" ]]; then
+            echo "${{ inputs.APP_NAME }}-upgrade NOT FOUND: Skipping..."
           else
-            echo "moodle-upgrade FOUND: Cleaning resources..."
-            oc delete job moodle-upgrade
-            echo "DELETED job moodle-upgrade"
+            echo "${{ inputs.APP_NAME }}-upgrade FOUND: Cleaning resources..."
+            oc delete job ${{ inputs.APP_NAME }}-upgrade
+            echo "DELETED job ${{ inputs.APP_NAME }}-upgrade"
           fi
 
       - name: 🧹️ Clean ${{ inputs.APP }}-${{ inputs.WEB_NAME }} | ${{ inputs.APP_HOST_URL }}
